patreon: cybercraft
custom:
  - https://coders.care/for/crowdfunding/l10nmgr-and-localizer
  - https://www.paypal.me/cybercraftsponsoring/150
  - https://www.amazon.de/gp/registry/wishlist/2I80GX9ZSMYXX
