stages:
  - lint

# Speed up builds
cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - .Build/vendor
    - public

default:
  image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

php-lint:
  stage: lint
  script:
    - composer run ci:php:lint
  rules:
    - allow_failure: false

php-cs-fixer:
  stage: lint
  before_script:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  script:
    - composer run ci:php:fixer
