services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Localizationteam\L10nmgr\:
    resource: '../Classes/*'

  Localizationteam\L10nmgr\Controller\ConfigurationManager:
    public: true

  Localizationteam\L10nmgr\Controller\TranslationTasks:
    public: true

  Localizationteam\L10nmgr\Controller\LocalizationManager:
    public: true

  Localizationteam\L10nmgr\Model\L10nBaseService:
    public: true

  Localizationteam\L10nmgr\Services\NotificationService:
    public: true
    arguments:
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $mailMessage: '@TYPO3\CMS\Core\Mail\MailMessage'

  Localizationteam\L10nmgr\Model\Tools\Tools:
    public: true
    arguments:
      $t8Tools: '@TYPO3\CMS\Backend\Configuration\TranslationConfigurationProvider'
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'

  Localizationteam\L10nmgr\Model\Tools\XmlTools:
    public: true
    arguments:
      $parseHTML: '@TYPO3\CMS\Core\Html\RteHtmlParser'

  Localizationteam\L10nmgr\LanguageRestriction\LanguageRestrictionRegistry:
    tags:
      - name: event.listener
        identifier: 'language-restriction-registry'
        method: 'addLanguageRestrictionDatabaseSchema'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  Localizationteam\L10nmgr\Command\Export:
    tags:
      - name: 'console.command'
        command: 'l10nmanager:export'
        schedulable: true

  Localizationteam\L10nmgr\Command\Import:
    tags:
      - name: 'console.command'
        command: 'l10nmanager:import'
        schedulable: true
