services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Localizationteam\L10nmgr\:
    resource: '../Classes/*'

  Localizationteam\L10nmgr\Controller\ConfigurationManager:
    public: true

  Localizationteam\L10nmgr\Controller\LocalizationManager:
    public: true

  Localizationteam\L10nmgr\Model\L10nBaseService:
    public: true

  Localizationteam\L10nmgr\Model\Tools\Tools:
    public: true

  Localizationteam\L10nmgr\Model\Tools\XmlTools:
    public: true
    arguments:
      $parseHTML: '@TYPO3\CMS\Core\Html\RteHtmlParser'

  Localizationteam\L10nmgr\LanguageRestriction\LanguageRestrictionRegistry:
    tags:
      - name: event.listener
        identifier: 'language-restriction-registry'
        method: 'addLanguageRestrictionDatabaseSchema'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  Localizationteam\L10nmgr\Command\Export:
    tags:
      - name: 'console.command'
        command: 'l10nmanager:export'
        schedulable: true

  Localizationteam\L10nmgr\Command\Import:
    tags:
      - name: 'console.command'
        command: 'l10nmanager:import'
        schedulable: true
